CFLAGS		+= -D_POSIX_SOURCE

BUILDDIR	= build
FORTIFY		= 1

AGP		= $(BUILDDIR)/AGP
AGP_SRCS	=			\
		AmiUtil/Application.c	\
		AmiUtil/Containers.c	\
		common.c		\
		html.c			\
		main.c			\
		markdown.c		\
		page.c			\
		rexx.c			\
		rss.c
AGP_OBJS	= $(patsubst %, $(BUILDDIR)/%.o, $(AGP_SRCS))

ifeq ($(FORTIFY),1)
	AGP_SRCS += AmiUtil/Fortify/Fortify.c
	CFLAGS += -DFORTIFY
endif

all: $(AGP)

clean:
	rm -fr $(BUILDDIR)

emubuild: $(AGP)
	@cp $< "/home/jay/Amiga/Share/"
